dist: trusty
language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "srvrguy-github"

jdk:
  - oraclejdk8

script:
  - |
    if [ "${TRAVIS_SECURE_ENV_VARS}" == "true" ]; then
      echo;
      echo "Running Build with SonarCloud Scanning";
      mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar $MAVEN_OPTIONS;
    else
      echo;
      echo "Running a normal test suite with no SonarCloud";
      mvn clean install;
    fi;

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
